[package]
name = "prj"
version = "0.1.0"
authors = ["Denys Vitali <denys@denv.it>"]

[dependencies]
postgres = { version= "0.15", features = ["with-chrono"] }
csv = "1.0.0-beta.5"
rust-crypto = "0.2.36"
serde="1.0"
serde_derive = "1.0"
chrono = "0.4"