version: '3'
services:
  server:
    build: .
    image: dvitali/gtfs-server:latest
    ports:
     - "80"
    env_file: .env.production
  postgres:
    image: "mdillon/postgis:latest"
    env_file: .env.production
