version: '3'
services:
  server:
    build: .
    image: dvitali/gtfs-server:latest
    ports:
     - "8000:8000"
    env_file: .env.production
  postgis:
    image: "mdillon/postgis:latest"
    env_file: .env.production
