(function() {var implementors = {};
implementors["gtfs_server"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"gtfs_server/models/dropoff/enum.DropOff.html\" title=\"enum gtfs_server::models::dropoff::DropOff\">DropOff</a>",synthetic:false,types:["gtfs_server::models::dropoff::DropOff"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"gtfs_server/models/pickup/enum.PickUp.html\" title=\"enum gtfs_server::models::pickup::PickUp\">PickUp</a>",synthetic:false,types:["gtfs_server::models::pickup::PickUp"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"gtfs_server/models/stop/struct.Stop.html\" title=\"struct gtfs_server::models::stop::Stop\">Stop</a>",synthetic:false,types:["gtfs_server::models::stop::Stop"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"gtfs_server/models/stop/struct.StopTrip.html\" title=\"struct gtfs_server::models::stop::StopTrip\">StopTrip</a>",synthetic:false,types:["gtfs_server::models::stop::StopTrip"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"gtfs_server/models/trip/struct.Trip.html\" title=\"struct gtfs_server::models::trip::Trip\">Trip</a>",synthetic:false,types:["gtfs_server::models::trip::Trip"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
